const menu = [{
        id: 1,
        title: 'Javascript ',
        category: 'Web',
        price: 15.99,
        img: './images/item-1.png',
        desc: `JavaScript for Beginners : Work closely with me doing exercises & learn more. I make Javascript easy for you guaranteed. `,
    },
    {
        id: 2,
        title: 'C#',
        category: 'Game',
        price: 13.99,
        img: './images/item-2.png',
        desc: `Learn how to write clean code in C#. Design and implement API based on the best practices developed by .NET community. `,
    },
    {
        id: 3,
        title: 'Flutter & Dart ',
        category: 'Mobile',
        price: 6.99,
        img: './images/item-3.png',
        desc: `A Complete Guide to the Flutter SDK & Flutter Framework for building native iOS and Android apps`,
    },
    {
        id: 4,
        title: 'PHP ',
        category: 'Web',
        price: 20.99,
        img: './images/item-4.png',
        desc: `PHP for Beginners: Learn to Code in PHP. Every line of code explained in detail. A true PHP for Beginners Course 2022 `,
    },
    {
        id: 5,
        title: 'C++',
        category: 'Game',
        price: 22.99,
        img: './images/item-5.png',
        desc: `Learn about move semantics, lambda expressions, smart pointers, concurrency, template, STL & more`,
    },
    {
        id: 6,
        title: 'React Native',
        category: 'Mobile',
        price: 18.99,
        img: './images/item-6.png',
        desc: `Use React Native and your React knowledge to build native iOS and Android Apps - incl. Push Notifications, Hooks, Redux`,
    },
    {
        id: 7,
        title: 'React JS',
        category: 'Web',
        price: 8.99,
        img: './images/item-7.png',
        desc: `Bootcamp on the React.js essentials. Gain a strong foundation of the core concepts, and build exciting and useful apps! `,
    },
    {
        id: 8,
        title: 'Unity',
        category: 'Game',
        price: 12.99,
        img: './images/item-8.png',
        desc: `Learn Unity in C# & Code Your First Five 2D Video Games for Web, Mac & PC. The Tutorials Cover Tilemap `,
    },
    {
        id: 9,
        title: 'Kotlin ',
        category: 'Mobile',
        price: 16.99,
        img: './images/item-9.png',
        desc: `Use Kotlin instead of Java. Kotlin is a new language that makes programming for Android or Javascript a dream.`,
    },
];
export default menu;